version: '3'

services:
  postgres:
    image: "postgres:14-bullseye"
    container_name: teamwize-postgres
    networks:
      - teamwize-network
    ports:
      - '5430:5432'
    environment:
      POSTGRES_DB: teamwize-db
      POSTGRES_USER: pg-admin
      POSTGRES_PASSWORD: pg-admin
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
  api:
    image: "ghcr.io/teamwize/api:dev"
    container_name: teamwize-api
    networks:
      - teamwize-network
    ports:
      - '8001:80'
    env_file:
      - .env
  app:
    image: "ghcr.io/teamwize/dashboard-app:latest"
    container_name: teamwize-app
    networks:
      - teamwize-network
    ports:
      - '8000:80'
networks:
  teamwize-network:
    external: true